config-dir = /usr/local/etc/letsencrypt
work-dir = /var/db/letsencrypt
logs-dir = /var/log/letsencrypt

server = https://acme-v02.api.letsencrypt.org/directory
email = admin@example.com

text = true
agree-tos = true
no-eff-email = true
non-interactive = true

authenticator = webroot
webroot-path = /usr/local/www
preferred-challenges = http-01

key-type = ecdsa
elliptic-curve = secp384r1
rsa-key-size = 3072

#pre-hook = /usr/local/etc/letsencrypt/renewal-hooks/pre/hook.sh
#post-hook = /usr/local/etc/letsencrypt/renewal-hooks/post/hook.sh
#deploy-hook = /usr/local/etc/letsencrypt/renewal-hooks/deploy/hook.sh