#!/bin/sh -eu

cat <<'EOF' > /etc/hosts
::1                        localhost localhost.localdomain devnull devnull.example.com
127.0.0.1                  localhost localhost.localdomain devnull devnull.example.com
EOF

cat <<'EOF' > /etc/pf.internal
fe80::/10
ff02::/16
10.0.0.0/8
__IPADDR4__/32
__IPADDR6__/64
EOF

ip4="`drill -a devnoip.example.com @localhost A | awk '/^devnoip/ {print $NF}'`"

if [ "$ip4" != '' ] && [ "$ip4" != 'record' ]
then
  echo "$ip4/32" >> /etc/pf.internal
  echo "$ip4 devnoip.example.com" >> /etc/hosts
fi

ip6="`drill -a devnoip.example.com @localhost AAAA | awk '/^devnoip/ {print $NF}'`"

if [ "$ip6" != '' ] && [ "$ip6" != 'record' ]
then
  echo "$ip6/64" >> /etc/pf.internal
  echo "$ip6 devnoip.example.com" >> /etc/hosts
fi

/sbin/pfctl -t internal -T replace `cat /etc/pf.internal` >/dev/null 2>&1

exit 0