driver = pgsql
connect = host=/tmp port=5432 dbname=postfixadmin user=postfix password=__PASSWORD_POSTFIX__
default_pass_scheme = ARGON2ID

iterate_query = \
  SELECT username AS user, \
  FROM mailbox \
  WHERE username = '%u' \
    AND (('%s' = 'smtp' AND smtp_active = true) \
      OR ('%s' <> 'smtp' AND active = true))

user_query = WITH candidate AS ( \
  SELECT \
    0 AS prio, \
    m.username AS user, \
    '/var/vmail/' || m.maildir AS home, \
    5000 AS uid, \
    5000 AS gid, \
    '*:bytes=' || m.quota AS quota_rule \
  FROM mailbox m \
  WHERE m.username = '%u' \
    AND (('%s' = 'smtp' AND m.smtp_active = true) \
      OR ('%s' <> 'smtp' AND m.active = true)) \
  UNION ALL \
  SELECT \
    1 AS prio, \
    m.username AS user, \
    '/var/vmail/' || m.maildir AS home, \
    5000 AS uid, \
    5000 AS gid, \
    '*:bytes=' || m.quota AS quota_rule \
  FROM alias a \
  JOIN mailbox m \
    ON m.username = a.goto \
  WHERE a.address = '%u' \
    AND (('%s' = 'smtp' AND m.smtp_active = true) \
      OR ('%s' <> 'smtp' AND m.active = true)) \
) \
SELECT user, home, uid, gid, quota_rule \
FROM candidate \
ORDER BY prio \
LIMIT 1;

password_query = WITH candidate AS ( \
  SELECT \
    0 AS prio, \
    m.username AS user, \
    m.password AS password, \
    '/var/vmail/' || m.maildir AS userdb_home, \
    5000 AS userdb_uid, \
    5000 AS userdb_gid, \
    '*:bytes=' || m.quota AS userdb_quota_rule \
  FROM mailbox m \
  WHERE m.username = '%u' \
    AND (('%s' = 'smtp' AND m.smtp_active = true) \
      OR ('%s' <> 'smtp' AND m.active = true)) \
  UNION ALL \
  SELECT \
    1 AS prio, \
    m.username AS user, \
    m.password AS password, \
    '/var/vmail/' || m.maildir AS userdb_home, \
    5000 AS userdb_uid, \
    5000 AS userdb_gid, \
    '*:bytes=' || m.quota AS userdb_quota_rule \
  FROM alias a \
  JOIN mailbox m \
    ON m.username = a.goto \
  WHERE a.address = '%u' \
    AND (('%s' = 'smtp' AND m.smtp_active = true) \
      OR ('%s' <> 'smtp' AND m.active = true)) \
) \
SELECT user, password, userdb_home, userdb_uid, userdb_gid, userdb_quota_rule \
FROM candidate \
ORDER BY prio \
LIMIT 1;