debugLevel = 1
TestOnly = 1
Reason_Message = Message {rejectdefer} due to: {spf}. Please see {url}
HELO_reject = SPF_Not_Pass
Mail_From_reject = Fail
No_Mail = False
PermError_reject = False
TempError_Defer = False
skip_addresses = 127.0.0.0/8,::ffff:127.0.0.0/104,::1
Header_Type = AR
Hide_Receiver = Yes
Authserv_Id = mail.example.com
Socket = local:/var/spool/postfix/pyspf-milter/pyspf-milter.sock
UserID = pyspf-milter
InternalHosts = 127.0.0.1
Mock = true
MacroList = daemon_name|VERIFYING