KERNCONF?=GENERIC MYKERNEL
PRINTERDEVICE=ascii
LICENSES_ACCEPTED+=EULA DCC
DISABLE_VULNERABILITIES=yes
.if ${.CURDIR:M/usr/ports/*}
OPTIONS_SET=CRYPTO GSSAPI_NONE ICONV ICU IDN IDN2 IPV6 LIBEDIT MAN3 MANPAGES NLS OPENSSL PCRE2 PGSQL SSL STRIP THREADS
OPTIONS_UNSET=BLACKLISTD DEBUG DOCS DOXYGEN DTRACE EXAMPLES GNUTLS GSSAPI GSSAPI_BASE GSSAPI_HEIMDAL GSSAPI_MIT INFO LDAP MEM_DEBUG STATIC TEST TESTS TRACE X11
.endif
DEFAULT_VERSIONS+=ssl=openssl35