AlwaysAddARHeader       yes
AuthservID              mail.example.com
AutoRestart             Yes
AutoRestartRate         10/1h
BaseDirectory           /var/run/opendkim
BodyLengthDB            refile:/usr/local/etc/mail/bodylengthdb.cfg
Canonicalization        relaxed/simple
LogWhy                  Yes
Mode                    sv
On-BadSignature         reject
OversignHeaders         From
PidFile                 /var/run/opendkim/opendkim.pid
ReportAddress           "DKIM Error Postmaster" <postmaster@example.com>
ReportBccAddress        admin@example.com
SendReports             Yes
SignatureAlgorithm      rsa-sha256
SMTPURI                 smtp://localhost
Socket                  local:/var/spool/postfix/opendkim/opendkim.sock
SubDomains              Yes
Syslog                  Yes
SyslogFacility          mail
SyslogSuccess           Yes
TrustAnchorFile         /usr/local/etc/unbound/root.key
UMask                   007
UserID                  opendkim
KeyTable                file:/usr/local/etc/mail/keytable
SigningTable            refile:/usr/local/etc/mail/signingtable
InternalHosts           refile:/usr/local/etc/mail/trustedhosts
ExternalIgnoreList      refile:/usr/local/etc/mail/trustedhosts
MacroList               dameon_name|ORIGINATING