AlwaysAddARHeader yes
AuthservID mail.example.com
AutoRestart Yes
AutoRestartRate 10/1h
BaseDirectory /var/run/milteropendkim
Canonicalization relaxed/relaxed
ExternalIgnoreList refile:/var/db/opendkim/trustedhosts
InternalHosts refile:/var/db/opendkim/trustedhosts
KeyTable /var/db/opendkim/keytable
LogWhy Yes
MacroList dameon_name|ORIGINATING
Mode sv
PidFile /var/run/milteropendkim/opendkim.pid
ReportAddress "DKIM Error Postmaster" <postmaster@example.com>
ReportBccAddress admin@example.com
SendReports Yes
SignatureAlgorithm rsa-sha256
SignHeaders From,Reply-To,To,Cc,In-Reply-To,References,Date,Subject,Content-Type,Content-Transfer-Encoding,MIME-Version
SigningTable refile:/var/db/opendkim/signingtable
SMTPURI smtp://localhost
#Socket inet:8891@localhost
Socket local:/var/run/milteropendkim/opendkim.sock
SubDomains Yes
Syslog Yes
SyslogFacility mail
SyslogSuccess Yes
TrustAnchorFile /usr/local/etc/unbound/root.key
UMask 022
UnboundConfigFile /usr/local/etc/unbound/unbound.conf
UserID mailnull:mailnull