AuthservID              mail.example.com
AutoRestart             Yes
AutoRestartRate         10/1h
BaseDirectory           /var/run/opendmarc
FailureReports          true
FailureReportsBcc       dmarc@example.com
FailureReportsOnNone    true
FailureReportsSentBy    postmaster@example.com
IgnoreAuthenticatedClients true
PidFile                 /var/run/opendmarc/opendmarc.pid
PublicSuffixList        /usr/local/share/public_suffix_list/public_suffix_list.dat
RejectFailures          false
RequiredHeaders         true
Socket                  local:/var/spool/postfix/opendmarc/opendmarc.sock
SPFIgnoreResults        true
SPFSelfValidate         true
Syslog                  true
SyslogFacility          mail
TrustedAuthservIDs      localhost,mail.example.com
UMask                   002
UserID                  opendmarc
HistoryFile             /usr/local/etc/mail/opendmarc.dat
IgnoreHosts             /usr/local/etc/mail/ignorehosts